name: Checks

on:
  push:
    branches-ignore:
      - master

jobs:
    commit_lint:
      name: "Lint commit messages"
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
      steps:
        - name: "Check out code"
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: "Lint commit messages"
          uses: wagoid/commitlint-github-action@v1
          with:
            failOnWarnings: true

    build_push:
      name: "Build & push Docker image"
      runs-on: ubuntu-latest
      needs: [commit_lint]

      # Only run this if we're in master
      if: github.ref == 'refs/heads/master'

      steps:
        - name: "Check out code"
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        # This provides the repository name, as well as the latest
        # version which is used as a tag
        - name: "Get docker info"
          id: docker_info
          run: make docker-info
        
        - name: "Build & push"
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
            repository: ${{ steps.docker_info.outputs.docker_repository }}
            tags: latest, ${{ steps.docker_info.outputs.docker_tag }}
