name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
    build_push:
      name: Build & push Docker image
      runs-on: ubuntu-latest
      if: github.event.base_ref == 'refs/heads/master'

      steps:
        - name: Check out code
          uses: actions/checkout@v2.3.1
          with:
            fetch-depth: 0

        - uses: satackey/action-docker-layer-caching@v0.0.4
          with:
            key: docker-layer-cache-{hash}
            restore-keys: |
              docker-layer-cache

        - name: Authenticate with Docker registry
          run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

        - name: Build & push
          run: make docker-push
