name: Sample Execution

on: push

jobs:
    test_toml:
      name: "Read TOML Sample"
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
      steps:
        - name: "Check out code"
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
  
        - name: "Read TOML"
          id: read_toml
          uses: ./
          with:
            path: sample.toml
            key: info.version

        - name: "Print output"
          run: echo ${{ steps.read_toml.outputs.info_version }}
