name: Sample Execution

on: push

jobs:
    test_toml:
      name: "Read TOML Sample"
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
      steps:
        - name: "Check out code"
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
  
        - name: "Read TOML"
          id: read_toml

          # We use the relative path here, instead of the absolute 'outcome-co/action-read-toml'
          # since it allows to not specify a branch (e.g. 'outcome-co/action-read-toml@master').
          # The workflow will always run using the code from the current branch, which is 
          # useful for testing
          uses: ./
          with:
            path: sample.toml
            key: info.version

        - name: "Print output"
          run: echo ${{ steps.read_toml.outputs.info_version }}
