name: Self Test

on:
  push:
    branches-ignore:
      - master


jobs:
  self_test:
    name: Self-Test
    runs-on: ubuntu-latest

    steps:
        - name: Check out code
          uses: actions/checkout@v2.3.4
          with:
            ref:  ${{ github.event.push.ref }}

        - name: Read Single Key
          id: rsk
          uses: ./test
          with:
            path: pyproject.toml
            key: sample.key_1

        - name: Test Single Key
          run: test ${{ steps.rsk.outputs.sample_key_1 }} = key_one

        - name: Read Multiple Keys
          id: rmk
          uses: ./test
          with:
            path: pyproject.toml
            key: |
              sample.key_1
              sample.key_2

        - name: Test Multiple Keys
          run: |
            test ${{ steps.rmk.outputs.sample_key_1 }} = key_one
            test ${{ steps.rmk.outputs.sample_key_2 }} = key_two
